-- | Stylesheet, script, and favicon for the static site. Semantic colour is
-- defined once as custom properties and reused on every page.
module Assets
  ( css
  , js
  , faviconSvg
  ) where

import Data.Text (Text)
import Data.Text qualified as T

css :: Text
css =
  T.unlines
    [ "/* nuprl-hs — semantic colour and decoration"
    , "   type      Prussian blue     types, universes, sorts"
    , "   binder    verdigris, dotted binding occurrences (λ, ∀, ∃, hyp names)"
    , "   connective oxblood          ∧ ∨ → ⇒ × ⊎ = ∈ ¬ ⊢"
    , "   tactic    forest            tactics and kernel rules"
    , "   extract   burnt sienna      computational content of a proof"
    , "   goal      ochre             sequent conclusions, turnstiles"
    , "   abs       slate indigo      named library abstractions"
    , "   value     ink               canonical inhabitants (Ax, pairs, λ)"
    , "   comment   faded ink, italic"
    , "   keyword   stone small-caps  theorem / abs / proof / qed"
    , "*/"
    , ":root {"
    , "  --paper: #f4efe6;"
    , "  --paper-raised: #fbf7f0;"
    , "  --ink: #1c1915;"
    , "  --ink-muted: #6a645a;"
    , "  --rule: #d9d0c0;"
    , "  --rule-strong: #b7aa94;"
    , "  --type: #1f4b8a;"
    , "  --binder: #0d6a62;"
    , "  --conn: #7a2c3a;"
    , "  --tac: #2f5d3a;"
    , "  --extract: #8a4b12;"
    , "  --goal: #6b5420;"
    , "  --abs: #3d4a7a;"
    , "  --val: #1c1915;"
    , "  --comment: #8a8376;"
    , "  --keyword: #5a5348;"
    , "  --num: #6b5420;"
    , "  --complete: #2f5d3a;"
    , "  --danger: #7a2c3a;"
    , "  --serif: \"Iowan Old Style\", Palatino, \"Palatino Linotype\", \"Book Antiqua\", Georgia, \"Times New Roman\", serif;"
    , "  --sans: \"Source Sans 3\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;"
    , "  --mono: \"Iosevka\", \"Source Code Pro\", \"IBM Plex Mono\", Menlo, Consolas, monospace;"
    , "  --measure: 42rem;"
    , "}"
    , "@media (prefers-color-scheme: dark) {"
    , "  :root {"
    , "    --paper: #161410;"
    , "    --paper-raised: #1e1b16;"
    , "    --ink: #ebe4d6;"
    , "    --ink-muted: #a39a8c;"
    , "    --rule: #3a342c;"
    , "    --rule-strong: #5c554a;"
    , "    --type: #8eb4e8;"
    , "    --binder: #6ec4bb;"
    , "    --conn: #d98996;"
    , "    --tac: #8fbf98;"
    , "    --extract: #e0a56a;"
    , "    --goal: #d4b56a;"
    , "    --abs: #a8b4e0;"
    , "    --val: #ebe4d6;"
    , "    --comment: #8a8376;"
    , "    --keyword: #c4bbae;"
    , "    --num: #d4b56a;"
    , "    --complete: #8fbf98;"
    , "    --danger: #d98996;"
    , "  }"
    , "}"
    , "* { box-sizing: border-box; }"
    , "html { font-size: 18px; color-scheme: light dark; }"
    , "body {"
    , "  margin: 0;"
    , "  color: var(--ink);"
    , "  background: var(--paper);"
    , "  font-family: var(--serif);"
    , "  line-height: 1.55;"
    , "  text-rendering: optimizeLegibility;"
    , "  -webkit-font-smoothing: antialiased;"
    , "}"
    , "a {"
    , "  color: inherit;"
    , "  text-decoration: underline;"
    , "  text-decoration-thickness: 1px;"
    , "  text-underline-offset: 0.18em;"
    , "  text-decoration-color: var(--rule-strong);"
    , "}"
    , "a:hover { text-decoration-color: var(--ink); }"
    , ".skip {"
    , "  position: absolute; left: -999px;"
    , "}"
    , ".skip:focus { left: 1rem; top: 1rem; background: var(--paper-raised); padding: 0.3rem 0.6rem; z-index: 10; }"
    , "header.site {"
    , "  border-bottom: 1px solid var(--rule);"
    , "  padding: 0.85rem 1.4rem;"
    , "  display: flex;"
    , "  justify-content: space-between;"
    , "  align-items: baseline;"
    , "  gap: 1rem;"
    , "  flex-wrap: wrap;"
    , "  background: var(--paper);"
    , "  position: sticky;"
    , "  top: 0;"
    , "  z-index: 5;"
    , "}"
    , "header.site .mark {"
    , "  font-variant: small-caps;"
    , "  letter-spacing: 0.12em;"
    , "  text-decoration: none;"
    , "  font-size: 1.05rem;"
    , "}"
    , "header.site nav { display: flex; gap: 1.1rem; flex-wrap: wrap; font-size: 0.92rem; color: var(--ink-muted); }"
    , "header.site nav a { text-decoration: none; }"
    , "header.site nav a:hover { color: var(--ink); }"
    , "main { padding: 2.2rem 1.4rem 4rem; }"
    , ".measure { max-width: var(--measure); margin: 0 auto; }"
    , "h1, h2, h3 { font-weight: 400; line-height: 1.25; }"
    , "h1 { font-size: 2.35rem; margin: 0 0 0.4rem; letter-spacing: -0.01em; }"
    , "h1 em { font-style: italic; font-weight: 400; }"
    , ".lede { font-size: 1.2rem; color: var(--ink-muted); margin: 0 0 1.6rem; }"
    , "h2 { font-size: 1.15rem; font-variant: small-caps; letter-spacing: 0.14em; margin: 2.6rem 0 0.8rem; border-top: 1px solid var(--rule); padding-top: 1.1rem; }"
    , "h3 { font-size: 1.05rem; margin: 1.6rem 0 0.4rem; }"
    , "p { margin: 0 0 0.9rem; }"
    , "p.note { color: var(--ink-muted); font-size: 0.95rem; }"
    , "code { font-family: var(--mono); font-size: 0.9em; white-space: nowrap; }"
    , "ul, ol { margin: 0 0 1rem; padding-left: 1.2rem; }"
    , "li { margin: 0.2rem 0; }"
    , "hr { border: 0; border-top: 1px solid var(--rule); margin: 2rem 0; }"
    , "footer.site { border-top: 1px solid var(--rule); padding: 1.4rem; color: var(--ink-muted); font-size: 0.88rem; text-align: center; }"
    , ".links { display: flex; flex-wrap: wrap; gap: 0.4rem 1.3rem; margin: 1.4rem 0 2.2rem; font-size: 0.95rem; }"
    , ".links a { text-decoration: none; border-bottom: 1px solid var(--rule-strong); }"
    , ".key { display: flex; flex-wrap: wrap; gap: 0.45rem 1.1rem; font-size: 0.82rem; margin: 1.2rem 0 0.4rem; }"
    , ".key span { white-space: nowrap; }"
    , ".sem-type, .key .sem-type { color: var(--type); }"
    , ".sem-binder, .key .sem-binder { color: var(--binder); border-bottom: 1px dotted var(--binder); }"
    , ".sem-conn, .key .sem-conn { color: var(--conn); font-weight: 500; }"
    , ".sem-tac, .key .sem-tac, .rule, .tac { color: var(--tac); }"
    , ".sem-extract, .key .sem-extract { color: var(--extract); }"
    , ".sem-goal, .key .sem-goal, .turnstile { color: var(--goal); }"
    , ".sem-abs, .key .sem-abs { color: var(--abs); font-style: italic; }"
    , ".sem-val { color: var(--val); }"
    , ".sem-var { color: var(--ink); }"
    , ".sem-kw { color: var(--keyword); font-variant: small-caps; letter-spacing: 0.04em; }"
    , ".sem-num { color: var(--num); }"
    , ".sem-comment { color: var(--comment); font-style: italic; }"
    , ".sem-keyword { color: var(--keyword); font-variant: small-caps; letter-spacing: 0.08em; }"
    , ".tm, .tac, .script, .sequent, .pnode-concl { font-family: var(--serif); }"
    , ".tm { cursor: help; }"
    , ".tac { cursor: help; }"
    , ".rule { cursor: help; font-variant: small-caps; letter-spacing: 0.06em; }"
    , ".ex-index { list-style: none; padding: 0; margin: 0 0 2rem; }"
    , ".ex-index li { display: grid; grid-template-columns: 2.2rem 1fr; gap: 0.8rem; padding: 0.85rem 0; border-bottom: 1px solid var(--rule); }"
    , ".ex-index .n { color: var(--ink-muted); font-variant-numeric: lining-nums; letter-spacing: 0.06em; font-size: 0.88rem; }"
    , ".ex-index a.title { text-decoration: none; font-size: 1.15rem; }"
    , ".ex-index a.title:hover { color: var(--type); }"
    , ".ex-index .tag { color: var(--ink-muted); font-size: 0.95rem; margin: 0.15rem 0 0; }"
    , ".ex-index .meta { font-size: 0.82rem; color: var(--ink-muted); margin-top: 0.2rem; }"
    , ".ex-index .meta .chap { color: var(--extract); }"
    , "dl.feats { margin: 0; }"
    , "dl.feats dt { font-variant: small-caps; letter-spacing: 0.08em; margin-top: 0.9rem; color: var(--type); }"
    , "dl.feats dd { margin: 0.15rem 0 0 0; color: var(--ink); }"
    , "blockquote { margin: 1rem 0; padding: 0 0 0 1rem; border-left: 2px solid var(--rule-strong); color: var(--ink-muted); font-style: italic; }"
    , ".ex-layout { max-width: 72rem; margin: 0 auto; }"
    , "@media (min-width: 960px) {"
    , "  .ex-layout { display: grid; grid-template-columns: 13.5rem minmax(0, 1fr); gap: 2.4rem; align-items: start; }"
    , "  .toc { position: sticky; top: 4.2rem; max-height: calc(100vh - 5rem); overflow: auto; }"
    , "}"
    , ".toc h2 { border: 0; padding: 0; margin: 0 0 0.6rem; font-size: 0.82rem; }"
    , ".toc ol { list-style: none; padding: 0; margin: 0; font-size: 0.88rem; }"
    , ".toc a { text-decoration: none; color: var(--ink-muted); display: block; padding: 0.12rem 0; }"
    , ".toc a:hover { color: var(--ink); }"
    , ".toc .abs-link { font-style: italic; color: var(--abs); }"
    , ".toolbar { display: flex; flex-wrap: wrap; gap: 0.5rem 0.9rem; margin: 0 0 1.4rem; font-size: 0.88rem; }"
    , ".toolbar button, .toolbar input {"
    , "  font-family: var(--serif);"
    , "  font-size: inherit;"
    , "  background: transparent;"
    , "  color: var(--ink);"
    , "  border: 0;"
    , "  border-bottom: 1px solid var(--rule-strong);"
    , "  padding: 0.15rem 0;"
    , "  cursor: pointer;"
    , "}"
    , ".toolbar button:hover { border-bottom-color: var(--ink); }"
    , ".toolbar input { min-width: 10rem; cursor: text; }"
    , ".card { border-top: 1px solid var(--rule); padding: 1.15rem 0 1.4rem; }"
    , ".card.hidden { display: none; }"
    , ".card-head { display: flex; justify-content: space-between; gap: 1rem; align-items: baseline; flex-wrap: wrap; }"
    , ".kind { font-variant: small-caps; letter-spacing: 0.1em; font-size: 0.78rem; color: var(--ink-muted); }"
    , ".kind.theorem { color: var(--tac); }"
    , ".kind.abs { color: var(--abs); }"
    , ".obj-name { font-size: 1.25rem; margin: 0.1rem 0 0.45rem; }"
    , ".status { font-size: 0.82rem; color: var(--complete); }"
    , ".status.bad { color: var(--danger); }"
    , ".statement { font-size: 1.08rem; margin: 0.3rem 0 0.7rem; line-height: 1.6; }"
    , ".extract-line { color: var(--extract); margin: 0.4rem 0 0.6rem; padding-left: 0.7rem; border-left: 2px solid var(--extract); }"
    , ".extract-line .k { font-variant: small-caps; letter-spacing: 0.08em; font-size: 0.78rem; color: var(--extract); margin-right: 0.5rem; }"
    , "details.panel { margin: 0.35rem 0; }"
    , "details.panel > summary { cursor: pointer; color: var(--ink-muted); font-variant: small-caps; letter-spacing: 0.08em; font-size: 0.82rem; list-style: none; }"
    , "details.panel > summary::-webkit-details-marker { display: none; }"
    , "details.panel > summary::before { content: \"▸ \"; color: var(--rule-strong); }"
    , "details.panel[open] > summary::before { content: \"▾ \"; }"
    , "details.panel > summary:hover { color: var(--ink); }"
    , ".script { margin: 0.5rem 0 0.2rem; padding-left: 1.3rem; }"
    , ".script li { margin: 0.15rem 0; }"
    , ".analysis { font-size: 0.92rem; color: var(--ink-muted); }"
    , ".analysis dt { font-variant: small-caps; letter-spacing: 0.06em; color: var(--ink); margin-top: 0.45rem; }"
    , ".analysis dd { margin: 0; }"
    , ".prose { color: var(--ink-muted); font-style: italic; margin: 0.6rem 0; }"
    , ".soft-line { color: var(--abs); font-size: 0.92rem; }"
    , ".proof-tree { margin: 0.6rem 0 0.2rem; }"
    , ".pnode { margin: 0.25rem 0 0.25rem 0.2rem; padding-left: 0.6rem; border-left: 1px solid var(--rule); }"
    , ".pnode > summary { cursor: pointer; list-style: none; }"
    , ".pnode > summary::-webkit-details-marker { display: none; }"
    , ".pnode-concl { color: var(--goal); }"
    , ".open-goal { color: var(--danger); padding: 0.3rem 0; }"
    , ".hyps { list-style: none; padding-left: 0; margin: 0.4rem 0; font-size: 0.95rem; }"
    , ".hyp-hidden { opacity: 0.55; font-style: italic; }"
    , ".hyp-idx { color: var(--ink-muted); font-size: 0.82rem; }"
    , ".concl { margin: 0.15rem 0 0.4rem; }"
    , ".turnstile { color: var(--goal); margin-right: 0.25rem; }"
    , ".node-extract { color: var(--extract); font-size: 0.9rem; margin: 0.2rem 0 0.4rem; padding-left: 0.5rem; border-left: 2px solid var(--extract); }"
    , ".node-extract .k { font-variant: small-caps; letter-spacing: 0.08em; font-size: 0.75rem; margin-right: 0.4rem; }"
    , ".subgoals { margin-top: 0.2rem; }"
    , "pre.source { overflow: auto; font-family: var(--mono); font-size: 0.78rem; line-height: 1.5; background: var(--paper-raised); border: 1px solid var(--rule); padding: 0.9rem 1rem; }"
    , "pre.source .ident { color: var(--ink); }"
    , "#tip {"
    , "  position: fixed;"
    , "  z-index: 20;"
    , "  max-width: min(28rem, 92vw);"
    , "  padding: 0.65rem 0.8rem;"
    , "  background: var(--paper-raised);"
    , "  color: var(--ink);"
    , "  border: 1px solid var(--rule-strong);"
    , "  box-shadow: 0 0.35rem 1.1rem rgba(28, 25, 21, 0.12);"
    , "  font-size: 0.84rem;"
    , "  line-height: 1.4;"
    , "  pointer-events: none;"
    , "}"
    , "#tip[hidden] { display: none; }"
    , "#tip .tip-kind { font-variant: small-caps; letter-spacing: 0.1em; font-size: 0.72rem; color: var(--ink-muted); }"
    , "#tip .tip-note { margin-top: 0.3rem; }"
    , "#tip .tip-row { font-family: var(--mono); font-size: 0.72rem; margin-top: 0.28rem; word-break: break-word; }"
    , "#tip .tip-row .k { color: var(--ink-muted); font-family: var(--serif); font-variant: small-caps; letter-spacing: 0.06em; margin-right: 0.35rem; }"
    , ".error { color: var(--danger); border-left: 2px solid var(--danger); padding-left: 0.7rem; }"
    , ".guide { color: var(--ink-muted); font-size: 0.95rem; }"
    , "@media print {"
    , "  header.site { position: static; }"
    , "  .toolbar, #tip { display: none !important; }"
    , "  details { open: 1; }"
    , "  a { text-decoration: none; }"
    , "}"
    ]

js :: Text
js =
  T.unlines
    [ "(function () {"
    , "  const tip = document.getElementById('tip');"
    , "  if (!tip) return;"
    , ""
    , "  function row(k, v) {"
    , "    if (!v) return '';"
    , "    const d = document.createElement('div');"
    , "    d.className = 'tip-row';"
    , "    d.innerHTML = '<span class=\"k\"></span><span class=\"v\"></span>';"
    , "    d.querySelector('.k').textContent = k;"
    , "    d.querySelector('.v').textContent = v;"
    , "    return d.outerHTML;"
    , "  }"
    , ""
    , "  function fill(el) {"
    , "    const kind = el.getAttribute('data-kind');"
    , "    const note = el.getAttribute('data-note');"
    , "    if (!kind && !note) return false;"
    , "    tip.innerHTML ="
    , "      (kind ? '<div class=\"tip-kind\"></div>' : '') +"
    , "      (note ? '<div class=\"tip-note\"></div>' : '') +"
    , "      row('uniform', el.getAttribute('data-uniform')) +"
    , "      row('unfolds', el.getAttribute('data-unfold')) +"
    , "      row('whnf', el.getAttribute('data-whnf')) +"
    , "      row('normal', el.getAttribute('data-nf'));"
    , "    const k = tip.querySelector('.tip-kind');"
    , "    if (k) k.textContent = kind;"
    , "    const n = tip.querySelector('.tip-note');"
    , "    if (n) n.textContent = note;"
    , "    return true;"
    , "  }"
    , ""
    , "  function place(ev) {"
    , "    const pad = 14;"
    , "    let x = ev.clientX + pad;"
    , "    let y = ev.clientY + pad;"
    , "    tip.hidden = false;"
    , "    const r = tip.getBoundingClientRect();"
    , "    if (x + r.width > window.innerWidth - 8) x = ev.clientX - r.width - pad;"
    , "    if (y + r.height > window.innerHeight - 8) y = ev.clientY - r.height - pad;"
    , "    if (x < 8) x = 8;"
    , "    if (y < 8) y = 8;"
    , "    tip.style.left = x + 'px';"
    , "    tip.style.top = y + 'px';"
    , "  }"
    , ""
    , "  let pinned = null;"
    , "  function show(ev) {"
    , "    const el = ev.target.closest('[data-kind]');"
    , "    if (!el || pinned) return;"
    , "    if (!fill(el)) return;"
    , "    place(ev);"
    , "  }"
    , "  function hide() { if (!pinned) tip.hidden = true; }"
    , ""
    , "  document.addEventListener('mousemove', function (ev) {"
    , "    if (pinned) return;"
    , "    const el = ev.target.closest('[data-kind]');"
    , "    if (!el) { hide(); return; }"
    , "    if (!fill(el)) return;"
    , "    place(ev);"
    , "  });"
    , "  document.addEventListener('click', function (ev) {"
    , "    const el = ev.target.closest('[data-kind]');"
    , "    if (!el) { pinned = null; hide(); return; }"
    , "    if (pinned === el) { pinned = null; hide(); return; }"
    , "    pinned = el;"
    , "    fill(el);"
    , "    place(ev);"
    , "  });"
    , "  document.addEventListener('keydown', function (ev) {"
    , "    if (ev.key === 'Escape') { pinned = null; hide(); }"
    , "  });"
    , ""
    , "  function all(sel, fn) { document.querySelectorAll(sel).forEach(fn); }"
    , "  const expandProofs = document.getElementById('expand-proofs');"
    , "  const collapseProofs = document.getElementById('collapse-proofs');"
    , "  if (expandProofs) expandProofs.addEventListener('click', function () {"
    , "    all('details.pnode', function (d) { d.open = true; });"
    , "    all('details.panel.proof-panel', function (d) { d.open = true; });"
    , "  });"
    , "  if (collapseProofs) collapseProofs.addEventListener('click', function () {"
    , "    all('details.pnode', function (d) { d.open = false; });"
    , "    const roots = document.querySelectorAll('details.panel.proof-panel > .proof-tree > details.pnode');"
    , "    roots.forEach(function (d) { d.open = true; });"
    , "  });"
    , "  const expandAll = document.getElementById('expand-all');"
    , "  if (expandAll) expandAll.addEventListener('click', function () {"
    , "    all('details.panel', function (d) { d.open = true; });"
    , "  });"
    , "  const q = document.getElementById('filter');"
    , "  if (q) q.addEventListener('input', function () {"
    , "    const s = q.value.toLowerCase().trim();"
    , "    all('.card[data-name]', function (c) {"
    , "      const n = (c.getAttribute('data-name') || '').toLowerCase();"
    , "      c.classList.toggle('hidden', s.length > 0 && n.indexOf(s) < 0);"
    , "    });"
    , "  });"
    , "})();"
    ]

faviconSvg :: Text
faviconSvg =
  T.unlines
    [ "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\">"
    , "  <rect width=\"32\" height=\"32\" fill=\"#f4efe6\"/>"
    , "  <text x=\"16\" y=\"23\" text-anchor=\"middle\""
    , "        font-family=\"Palatino, Georgia, serif\" font-size=\"20\" fill=\"#1f4b8a\">⊢</text>"
    , "</svg>"
    ]
